---
title: FATORES DE RISCO PARA ÓBITO POR HANTAVIROSE NO PARANÁ, 1992-2016, ABORDAGEM VIA UM MODELO DE FRAÇÃO DE CURA.
author1: Pedro Henrique Pavan Gonçalves
advisor: Silvia Emiko Shimakura
year: 2022
dedicatoria: |
  `r if(knitr:::is_latex_output()) paste(readLines("dedicatoria.Rmd"),
  collapse = '\n  ')`
thanks: |
  `r if(knitr:::is_latex_output()) paste(readLines("agradecimentos.Rmd"),
  collapse = '\n  ')`
epigrafe: |
  `r if(knitr:::is_latex_output()) paste(readLines("epigrafe.Rmd"),
  collapse = '\n  ')`
resumo: |
  `r if(knitr:::is_latex_output()) paste(readLines("resumo.Rmd"),
  collapse = '\n  ')`
palavras-chave: [Palavra-chave 1, Palavra-chave 2]
output: tcctemplate::tcc_template
---


```{r setup, include=FALSE}
library(xtable)
## Opções comuns utilizadas em todas as tabelas usando xtable
options(xtable.caption.placement = "top",
        xtable.include.rownames = FALSE,
        xtable.comment = FALSE)
## Opções comuns para o knitr
knitr::opts_chunk$set(echo = FALSE,
                      out.width = "80%",
                      fig.align = "center")
```

# Introdução
\bigskip

```{r, child="introducao.Rmd"}
```

# Objetivos 
\bigskip

```{r, child="objetivos.Rmd"}
```

# Revisão de Literatura 
\bigskip

```{r, child="revisao.Rmd"}
```

# Material e Métodos
\bigskip

```{r, child="metodologia.Rmd"}
```

# Resultados e Discussão
\bigskip

```{r, child="resultados.Rmd"}
```

# Considerações Finais
\bigskip

```{r, child="consideracoes.Rmd"}
```

```{r, echo=FALSE}
## Se houverem apêndices ou anexos, coloque aqui como TRUE e veja os
## chinks a seguir
apendice <- FALSE
anexo <- FALSE
```

\setlength{\afterchapskip}{\baselineskip}
\bibliography{bib/ref.bib}

\postextual

```{r, child=if(apendice) "apendice01.Rmd"}
```

```{r, child=if(anexo) "anexo01.Rmd"}
```
